baseURL = 'https://poradnik-rodzica.myops.pl/'
languageCode = 'pl-pl'
defaultContentLanguage = 'pl'
title = 'Poradnik Rodzica'

# Use module instead of theme
[module]
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

# Site parameters
[params]
    mainSections = ['posts']
    featuredImageField = 'featured_image'
    rssFullContent = true
    favicon = '/favicon.png'

    [params.footer]
        since = 2025
        customText = ''

    [params.sidebar]
        emoji = 'ðŸ‘¶'
        subtitle = 'Praktyczne porady dla rodzicÃ³w'
        
    [params.sidebar.avatar]
        enabled = false
        
    [params.article]
        math = false
        toc = true
        readingTime = true
        [params.article.image]
            enabled = true
            width = "100%"
            height = "auto"
            style = "image-rendering: crisp-edges;"
        
    [params.comments]
        enabled = true
        provider = 'disqus'
        
        [params.comments.disqus]
            shortname = 'your-disqus-shortname'

    [params.widgets]
        enabled = ['search', 'archives', 'tag-cloud']
        
        [params.widgets.archives]
            limit = 5
            
        [params.widgets.tagCloud]
            limit = 20

    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
            
    [params.defaultImage]
        [params.defaultImage.article]
            enabled = false
        [params.defaultImage.opengraph]
            enabled = false
            
# Menu config
[menu]
    [[menu.main]]
        identifier = 'home'
        name = 'Start'
        url = '/'
        weight = -100
        params = { icon = 'home' }
        
    [[menu.main]]
        identifier = 'about'
        name = 'O nas'
        url = '/o-nas/'
        weight = -90
        params = { icon = 'user' }
        
    [[menu.main]]
        identifier = 'categories'
        name = 'Kategorie'
        url = '/categories'
        weight = -80
        params = { icon = 'folder' }

# Custom output formats
[outputs]
    home = ['HTML', 'RSS', 'JSON']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true  # Allow HTML in markdown

    [markup.highlight]
        noClasses = false
        
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2

# Add custom CSS
[params.customCSS]
    css = ['/css/custom.css']